// The "video spec" is the contract between the pipeline (which generates data)
// and Remotion (which renders it). Phase 1 uses a hardcoded example; later
// phases will have Gemini produce this JSON.

export type LngLat = [number, number];

export interface CameraState {
  center: LngLat;
  zoom: number;
  pitch?: number;
  bearing?: number;
}

export interface CameraBeat extends CameraState {
  /** Frame at which the camera should be at this state. */
  atFrame: number;
}

export interface SpriteSpec {
  /** Path under public/ for a generated sprite PNG, e.g. "sprites/ship.png".
   *  If omitted, the built-in inline SVG ship is used. */
  image?: string;
  /** Rendered size in px (default 72). */
  size?: number;
}

export interface RouteSpec {
  coordinates: LngLat[];
  revealStartFrame: number;
  revealEndFrame: number;
  /** If true, the camera follows the leading point of the revealed route. */
  cameraFollows?: boolean;
  /** The marker that rides the leading point of the route. */
  sprite?: SpriteSpec;
}

export interface Overlay {
  text: string;
  atFrame: number;
  durationFrames: number;
  kind: "title" | "year" | "caption";
}

export interface Narration {
  /** Path under public/ for the TTS audio, e.g. "narration/example.mp3". */
  audioSrc?: string;
  /** Path under public/ for the SRT captions, e.g. "narration/example.srt". */
  srtSrc?: string;
}

export interface VideoSpec {
  id: string;
  fps: number;
  durationInFrames: number;
  width: number;
  height: number;
  /** "local-countries" for the offline basemap, or a MapLibre/Mapbox style URL. */
  mapStyleUrl: string;
  camera: CameraBeat[];
  route: RouteSpec;
  overlays: Overlay[];
  /** Optional voiceover + synced captions (Phase 2, generated by pipeline/voice.ts). */
  narration?: Narration;
}
